WITH get_median AS (
    SELECT 
        PERCENTILE_CONT(0.5) WITHIN GROUP (
            ORDER BY NULLIF(TRIM("CONSTRUCTION_VALUE"::text), '')::NUMERIC
        ) AS construction_median_value 
    FROM kitchener_buildings_permits
)
select p.*,
	EXTRACT(month from p."APPLICATION_DATE") as "APPLICATION_MONTH", --extract month
	--handling variations of distinct values and categorizing
	--trim(upper()) is to get rid of accidental variation in capitals and spaces
	CASE
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'NEW CONSTRUCTION', 'NEW', 'SHELL ONLY CONSTRUCTION', 'INSTALLATION OF PRE-FABRICATED BUILDING', 'FOUNDATION - ONLY' ) THEN 'New Construction'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'ADDITION TO BUILDING', 'ADDITION TO BUILDING (INCLUDING MEZZANINE)', 'ADDITION OF MEZZANINE', 'ADDITION OF OUTDOOR PATIO', 'NEW ROOF STRUCTURE' ) THEN 'Addition'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'INTERIOR ALTERATION', 'ALTERATIONS/IMPROVEMENTS', 'EXTERIOR ALTERATION', 'INTERIOR FINISH', 'PARTITIONS', 'STOREFRONT REPLACEMENT', 'DEMISING WALL', 'CEILING', 'NEW ENTRY', 'BALCONY GUARD', 'RECLAD WALL', 'ALTERATION', 'ALTERATIONS / IMPROVEMENTS TO BUILDING', 'ALTERATIONS / IMPROVEMENTS', 'CANOPY' ) THEN 'Alteration & Renovation'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'SINGLE DWELLING CONVERTED TO MULTIPLE DWELLING', 'ALTERATIONS TO CREATE ADDITIONAL DWELLING UNIT(S)', 'MULTIPLE DWELLING CONVERTED TO MULTIPLE DWELLING', 'ALTERATIONS WITH LOSS OF DWELLING UNIT(S)', 'NON-RESIDENTIAL CONVERTED TO RESIDENTIAL BUILDING', 'SINGLE DWELLING CONVERTED TO NON-RESIDENTIAL BUILDING' ) THEN 'Building Conversion'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'DEMOLITION OF RESIDENTIAL UNIT(S)', 'MINOR DEMOLITION', 'DEMOLITION NON-RES', 'DEMO PARTIAL NON-RES', 'FULL / PARTIAL DEMOLITION WITH LOSS OF DWELLING UNIT(S)', 'FULL / PARTIAL DEMOLITION WITH NO LOSS OF DWELLING UNIT(S)', 'DEMO INTERIOR PARTITIONS', 'DEMO OF RES & NON-RES UNIT(S)', 'FULL / PARTIAL DEMOLITION (LOSS OF FLOOR AREA INCLUDING MEZZANINE)' ) THEN 'Demolition'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'ALTERATION OF PLUMBING', 'NEW BACKFLOW DEVICE', 'CONNECT TO STORM OR SANITARY', 'ELECTRICAL ALTERATION', 'ADDITION OF FIXTURES', 'MECHANICAL ADDITION', 'MECHANICAL ALTERATION', 'ELECTRICAL ADDITION', 'BACKFLOW DEVICE', 'MECHANICAL', 'ELECTRICAL', 'PRESSURE REDUCING VALVE', 'WASHROOM' ) THEN 'Systems & Utilities'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'SEPTIC SYSTEM INSTALLATION', 'DISCONNECT FROM SEPTIC', 'SEPTIC', 'SEPTIC SYSTEM MAJOR REPAIR', 'SEPTIC SYSTEM MINOR REPAIR' ) THEN 'Septic Systems'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'PERMIT REVISION - MINOR REVISION', 'PERMIT REVISION - ADDITIONAL UNITS', 'PERMIT REVISION - ADDITIONAL M2', 'PERMIT REVISION - REDUCING UNITS', 'PERMIT REVISION - REDUCING M2', 'PERMIT REVISION - ADDITIONAL M2 + ADDITIONAL UNITS' ) THEN 'Permit Revision'
		WHEN TRIM(UPPER(p."WORK_TYPE")) IN ( 'SITE SERVICES', 'DESIGNATED STRUCTURE', 'RETAINING WALL', 'ELEVATOR/ESCALATOR/LIFT', 'TEMPORARY INSTALLATION', 'NEW, ADDITION OR ALTERATION', 'SITE SERVICING', 'PHASE', 'CONDITIONAL', 'INDOOR PUBLIC POOL OR SPA' ) THEN 'Special Infrastructure & Misc'
		ELSE 'Unknown' --also handle nulls
	END AS "WORK_TYPE_CLEAN",
	CASE
		WHEN TRIM(UPPER(p."PERMIT_TYPE")) IN ( 'RESIDENTIAL BUILDING (HOUSE)', 'RESIDENTIAL BUILDING (MULTI)', 'ZZREPEAT RESIDENTIAL BUILDING', 'RESIDENTIAL DEMOLITION', 'RESIDENTIAL ACCESSORY (1 OR 2 UNITS)', 'RESIDENTIAL ALTERATION', 'RESIDENTIAL GARAGE/CARPORT (1 OR 2 UNITS)', 'RESIDENTIAL ACCESSORY (3 OR MORE)', 'RESIDENTIAL GARAGE/CARPORT (3 OR MORE)', 'RESIDENTIAL BUILDING PERMIT', 'ZZOLD RESIDENTIAL BUILDING (OTHER)' ) THEN 'Residential'
		WHEN TRIM(UPPER(p."PERMIT_TYPE")) IN ( 'INDUSTRIAL BUILDING', 'NON-RESIDENTIAL ALTERATION', 'COMMERCIAL BUILDING', 'NON-RESIDENTIAL DEMOLITION', 'FARM BUILDING', 'MULTIPLE USE BUILDING', 'MIXED USE BUILDING PERMIT', 'FARM BUILDING PERMIT' ) THEN 'Commercial & Industrial'
		WHEN TRIM(UPPER(p."PERMIT_TYPE")) IN ( 'SCHOOL PORTABLES', 'GOV''T/INSTITUTIONAL BUILDING' ) THEN 'Institutional & Government'
		WHEN TRIM(UPPER(p."PERMIT_TYPE")) IN ( 'SEPTIC SYSTEM', 'PLUMBING', 'ELECTRICAL', 'MECHANICAL' ) THEN 'Trades & Utilities'
		WHEN TRIM(UPPER(p."PERMIT_TYPE")) IN ( 'PERMANENT SIGN PERMITS', 'GARDEN CENTRE/TENT', 'MISCELLANEOUS BUILDING PERMIT', 'OTHER BUILDING APPROVALS', 'INDUSTRIAL/COMMERCIAL/INSTITUTIONAL BUILDING PERMIT' ) THEN 'Other/Mixed Approvals'
		ELSE 'Unknown'
	END AS "PERMIT_TYPE_CLEAN",
	--hanlding null values and filling in missing construction $ with median $
	COALESCE(p."FINAL_DATE"::text, 'Unfinished') AS "FINAL_DATE_CLEAN",
	COALESCE(p."CONSTRUCTION_VALUE", construction_median_value) AS "CONSTRUCTION_VALUE_CLEAN"
FROM kitchener_buildings_permits p
CROSS JOIN get_median m
where 
	p."APPLICATION_DATE" IS NOT NULL
    AND p."ISSUE_DATE" IS NOT NULL
    AND p."ISSUED_BY" IS NOT NULL
    AND p."PERMIT_FEE" IS NOT NULL