table permits_modeling_data
	lineageTag: 2b1c9ac9-91d1-43d8-9754-d9e2cf35a0c6

	column APPLICATION_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a2d6583-2f30-4621-ae6d-4917c371a0be
		summarizeBy: none
		sourceColumn: APPLICATION_DATE

		variation Variation
			isDefault
			relationship: 10a98cae-d6eb-4656-8983-cc0953883cc2
			defaultHierarchy: LocalDateTable_a0f009b1-ab6b-47e9-bff0-bc4baa78c7ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CONSTRUCTION_VALUE_CLEAN
		dataType: int64
		formatString: 0
		lineageTag: c28c0987-7d5c-4f80-86db-0d938929af4e
		summarizeBy: sum
		sourceColumn: CONSTRUCTION_VALUE_CLEAN

		annotation SummarizationSetBy = Automatic

	column PERMIT_TYPE_CLEAN
		dataType: string
		lineageTag: 5961fac4-cec2-417b-b058-a60b0ac79f82
		summarizeBy: none
		sourceColumn: PERMIT_TYPE_CLEAN

		annotation SummarizationSetBy = Automatic

	column WORK_TYPE_CLEAN
		dataType: string
		lineageTag: 942e5a43-fd2f-4bd8-bb18-21dc4f5b71a2
		summarizeBy: none
		sourceColumn: WORK_TYPE_CLEAN

		annotation SummarizationSetBy = Automatic

	column WARD
		dataType: int64
		formatString: 0
		lineageTag: 80cbbfaf-52e2-4e61-8052-a57ca3636560
		summarizeBy: sum
		sourceColumn: WARD

		annotation SummarizationSetBy = Automatic

	column APPLICATION_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 3dfd7772-eb18-4579-a5f5-1334f0c268c2
		summarizeBy: sum
		sourceColumn: APPLICATION_MONTH

		annotation SummarizationSetBy = Automatic

	column APPROVAL_DURATION
		dataType: int64
		formatString: 0
		lineageTag: db61ad21-df7f-4a37-bd83-97f39fdac981
		summarizeBy: sum
		sourceColumn: APPROVAL_DURATION

		annotation SummarizationSetBy = Automatic

	partition permits_modeling_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sophi\OneDrive\Documents\vscode\powerbi\permits_modeling_data.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"APPLICATION_DATE", type date}, {"CONSTRUCTION_VALUE_CLEAN", Int64.Type}, {"PERMIT_TYPE_CLEAN", type text}, {"WORK_TYPE_CLEAN", type text}, {"WARD", Int64.Type}, {"APPLICATION_MONTH", Int64.Type}, {"APPROVAL_DURATION", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

